[package]
name = "quad"
version = "0.1.0"
authors = ["Niklas Claesson <nicke.claesson@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["dylib", "staticlib"]

[dependencies]
epics-sys = "*"
paste = "0.1"

[build-dependencies]
bindgen = "0.32.1"
